const arena=document.querySelector('#arena'), target=document.querySelector('#target'), reticle=document.querySelector('#reticle');
const state={mode:'flick',running:false,time:30,score:0,hits:0,shots:0,reactions:[],spawned:0,startAt:0,lastSpawn:0,sound:true};
const configs={flick:{label:'FLICK LAB',title:'Warm-up flicks',tip:'Relax your grip. Let the mouse glide, then click with intent.',size:78,points:100},track:{label:'TRACK RUN',title:'Hold the line',tip:'Keep your eyes on the target, then make small, steady corrections.',size:60,points:120},precision:{label:'PRECISION',title:'Zero waste',tip:'Slow is smooth. Build the habit of stopping exactly on center.',size:38,points:180}};
const $=s=>document.querySelector(s); function pad(n){return String(n).padStart(2,'0')}
function setMode(m){state.mode=m;document.querySelectorAll('.mode').forEach(b=>b.classList.toggle('active',b.dataset.mode===m));const c=configs[m];$('#modeLabel').textContent=c.label;$('#drillTitle').textContent=c.title;$('#coachTip').textContent=c.tip;target.style.width=target.style.height=c.size+'px';reset()}
function reset(){state.running=false;state.paused=false;state.time=+$duration.value;state.score=state.hits=state.shots=state.spawned=0;state.reactions=[];target.hidden=true;$('#arenaHint').hidden=false;$('#startLabel').textContent='START ROUND';$('#sessionStatus').textContent='READY TO TRAIN';update()}
function update(){ $('#timeStat').textContent=`00:${pad(state.time)}`;$('#scoreStat').textContent=String(state.score).padStart(4,'0');$('#hitsStat').textContent=state.hits;$('#accuracyStat').textContent=state.shots?Math.round(state.hits/state.shots*100)+'%':'—';let best=localStorage.getItem('vector-best-'+state.mode)||0;$('#bestStat').textContent=String(best).padStart(4,'0')}
function spawn(){const r=arena.getBoundingClientRect(), pad=70;target.style.left=(pad+Math.random()*(r.width-pad*2))+'px';target.style.top=(pad+Math.random()*(r.height-pad*2))+'px';target.hidden=false;state.lastSpawn=performance.now();state.spawned++;}
function start(){if(state.running)return;if(state.paused){state.paused=false;state.running=true;state.startAt=performance.now()-(+.value-state.time)*1000;#sessionStatus.textContent='ROUND LIVE';#startLabel.textContent='ROUND LIVE';tick();return}state.running=true;state.time=+$duration.value;state.score=state.hits=state.shots=0;state.reactions=[];$('#arenaHint').hidden=true;$('#startLabel').textContent='ROUND LIVE';$('#sessionStatus').textContent='ROUND LIVE';spawn();update();state.startAt=performance.now();tick()}
function tick(){if(!state.running)return;let elapsed=Math.floor((performance.now()-state.startAt)/1000);state.time=Math.max(0,+$duration.value-elapsed);update();if(state.time<=0){finish();return}requestAnimationFrame(tick)}
function finish(){state.running=false;target.hidden=true;$('#sessionStatus').textContent='ROUND COMPLETE';$('#startLabel').textContent='START ROUND';let acc=state.shots?Math.round(state.hits/state.shots*100):0, avg=state.reactions.length?Math.round(state.reactions.reduce((a,b)=>a+b,0)/state.reactions.length):0;let old=+(localStorage.getItem('vector-best-'+state.mode)||0);if(state.score>old)localStorage.setItem('vector-best-'+state.mode,state.score);$('#resultScore').textContent=String(state.score).padStart(4,'0');$('#resultAccuracy').textContent=acc+'%';$('#resultReaction').textContent=avg+' ms';$('#resultTitle').textContent=state.score>old&&state.score>0?'New personal best.':'Clean work.';$('#results').hidden=false;update()}
arena.addEventListener('mousemove',e=>{const r=arena.getBoundingClientRect();reticle.style.left=e.clientX-r.left+'px';reticle.style.top=e.clientY-r.top+'px'});arena.addEventListener('mousedown',e=>{if(!state.running)return;state.shots++;if(e.target.closest&&e.target.closest('#target')){state.hits++;state.score+=configs[state.mode].points;state.reactions.push(performance.now()-state.lastSpawn);$('#hitFlash').classList.remove('flash');void $('#hitFlash').offsetWidth;$('#hitFlash').classList.add('flash');spawn()}update()});
document.querySelectorAll('.mode').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));const $duration=$('#duration');$duration.onchange=reset;$('#startBtn').onclick=start;$('#againBtn').onclick=()=>{$('#results').hidden=true;start()};$('#resetBtn').onclick=reset;$('#soundToggle').onclick=()=>{state.sound=!state.sound;$('#soundToggle').textContent=state.sound?'◒ SOUND':'◒ MUTED'};document.addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();if($('#results').hidden)start();else{$('#results').hidden=true;start()}}if(e.code==='Escape'&&state.running){state.running=false;state.paused=true;$('#sessionStatus').textContent='PAUSED';$('#startLabel').textContent='RESUME';}});reset();


